'use client'

import * as Select from '@radix-ui/react-select'
import type { ReactNode } from 'react'
import { Check, ChevronDown } from 'lucide-react'

type Option = { value: string; label: ReactNode }
type Props = { value: string; onValueChange: (value: string) => void; placeholder?: string; options: Option[]; className?: string; 'aria-label'?: string; forceDown?: boolean }

export function StyledSelect({ value, onValueChange, placeholder, options, className = '', 'aria-label': ariaLabel, forceDown = false }: Props) {
  const attendanceMode = options.length === 4 && options.every((option) => ['PRESENT', 'ABSENT_UNEXCUSED', 'ABSENT_EXCUSED', 'LATE'].includes(option.value))
  const selectableOptions = options.filter((option) => option.value !== '')
  if (attendanceMode) return <div className={`flex flex-nowrap gap-1.5 ${className}`} aria-label={ariaLabel}>{options.map((option) => { const selected = value === option.value; const palette = !selected ? 'border-slate-300 bg-slate-100 text-slate-600 hover:bg-slate-200 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700' : option.value === 'PRESENT' ? 'border-emerald-600 bg-emerald-500 text-white shadow-[0_0_12px_rgba(16,185,129,0.75)]' : option.value === 'ABSENT_UNEXCUSED' ? 'border-red-700 bg-red-600 text-white shadow-[0_0_12px_rgba(239,68,68,0.75)]' : option.value === 'ABSENT_EXCUSED' ? 'border-sky-700 bg-sky-600 text-white shadow-[0_0_12px_rgba(14,165,233,0.75)]' : 'border-yellow-600 bg-yellow-400 text-yellow-950 shadow-[0_0_12px_rgba(234,179,8,0.8)]'; return <button key={option.value} type="button" onClick={() => onValueChange(option.value)} className={`min-w-[4.75rem] whitespace-nowrap rounded-md border px-4 py-1.5 text-[11px] font-bold transition ${palette}`}>{option.label}</button> })}</div>
  return <Select.Root value={value || undefined} onValueChange={onValueChange}><Select.Trigger aria-label={ariaLabel} className={`relative flex h-10 w-full items-center justify-between rounded-xl border border-border bg-card px-3 pe-10 ps-3 text-start text-sm text-foreground transition hover:bg-accent focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-0 focus-visible:ring-2 data-[state=open]:bg-accent ${className}`}><Select.Value placeholder={placeholder} /><Select.Icon className="absolute end-3"><ChevronDown className="h-4 w-4 text-foreground/55" /></Select.Icon></Select.Trigger><Select.Portal><Select.Content position="popper" side="bottom" align="start" sideOffset={4} avoidCollisions={!forceDown} className="z-[1100] max-h-[min(60vh,24rem,var(--radix-select-content-available-height))] min-w-[var(--radix-select-trigger-width)] overflow-hidden rounded-xl border border-border bg-card p-1 text-foreground shadow-2xl"><Select.ScrollUpButton className="flex h-6 items-center justify-center bg-card"><ChevronDown className="h-4 w-4 rotate-180" /></Select.ScrollUpButton><Select.Viewport className="max-h-[min(60vh,22rem,var(--radix-select-content-available-height))] overflow-y-auto">{selectableOptions.map((option) => <Select.Item key={option.value} value={option.value} className="flex cursor-pointer items-center justify-between rounded-lg px-3 py-2 text-sm text-foreground outline-none data-[highlighted]:bg-accent"><Select.ItemText>{option.label}</Select.ItemText><Select.ItemIndicator><Check className="h-4 w-4 text-emerald-500" /></Select.ItemIndicator></Select.Item>)}</Select.Viewport><Select.ScrollDownButton className="flex h-6 items-center justify-center bg-card"><ChevronDown className="h-4 w-4 rotate-180" /></Select.ScrollDownButton></Select.Content></Select.Portal></Select.Root>
}
